# Generated by Django 6.0 on 2025-12-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('novo', 'Em Negociação'), ('confirmado', 'Confirmado/Preparação'), ('finalizado', 'Registrado no Caderno')], default='novo', max_length=20),
        ),
    ]
