# Generated by Django 6.0 on 2025-12-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_possui_sabores_itempedido_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sabor',
            options={'verbose_name': 'Sabor', 'verbose_name_plural': 'Sabores'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='possui_sabores',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='sabor',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='ordem_exibicao',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='preco_adicional',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='sabor_escolhido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='sabores',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='produtos.sabor'),
        ),
        migrations.AddField(
            model_name='sabor',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ProdutoSabor',
        ),
    ]
