# Generated by Django 6.0 on 2025-12-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='possui_sabores',
            field=models.BooleanField(default=False, help_text='Produtos desta categoria podem ter seleção de sabores', verbose_name='Pode ter sabores?'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações do cliente'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='sabor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sabor escolhido'),
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Sabor')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preço Adicional')),
                ('ordem_exibicao', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoria onde este sabor é mais comum', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria', verbose_name='Categoria Sugerida')),
            ],
            options={
                'verbose_name': 'Sabor',
                'verbose_name_plural': 'Sabores',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores_disponiveis', to='produtos.produto')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.sabor')),
            ],
            options={
                'verbose_name': 'Sabor Disponivel',
                'verbose_name_plural': 'Sabores Disponíveis',
                'ordering': ['ordem', 'sabor__nome'],
                'unique_together': {('produto', 'sabor')},
            },
        ),
    ]
