# Generated by Django 6.0 on 2025-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_sabor_options_remove_categoria_possui_sabores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('novo', 'Em Negociação'), ('confirmado', 'Confirmado/Preparação'), ('finalizado', 'Finalizado'), ('registrado', 'Registrado no Caderno'), ('cancelado', 'Cancelado')], default='novo', max_length=20),
        ),
    ]
