# Generated by Django 6.0 on 2026-01-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_pedido_endereco_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quanto você pagou pelo produto', max_digits=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço de Venda'),
        ),
    ]
